apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: submission-checker
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:password@db:5432/submission_checker?sslmode=require&pgbouncer=true"
  BETTER_AUTH_SECRET: "change-this-to-a-random-32-char-string"
  NEO4J_PASSWORD: "password"
